{{ config(
    materialized='view'
) }}

SELECT
    STATE_KEY,
    STATE_FIPS,
    STATE_NAME,
    STATE_ABBREV,

    TOTAL_HPSA_DESIGNATIONS,
    FACILITY_HPSA_COUNT,
    POPULATION_GROUP_HPSA_COUNT,
    GEOGRAPHIC_AREA_HPSA_COUNT,

    ACS_INSURANCE_POPULATION,
    PCT_INSURED,
    PCT_UNINSURED,
    UNINSURED_POPULATION,

    ACS_POVERTY_POPULATION,
    PCT_BELOW_POVERTY,
    ESTIMATED_POPULATION_BELOW_POVERTY

FROM {{ ref('fact_healthcare_access') }}