{{ config(
    materialized='view'
) }}

SELECT
    STATE_KEY,
    STATE_FIPS,
    STATE_NAME,
    STATE_ABBREV,

    AHRF_POPULATION,

    PHYSICIANS_PER_100K,
    OFFICE_PHYSICIANS_PER_100K,
    PA_PER_100K,
    RN_PER_100K,
    APRN_PER_100K,

    TOTAL_HPSA_DESIGNATIONS,
    FACILITY_HPSA_COUNT,
    POPULATION_GROUP_HPSA_COUNT,
    GEOGRAPHIC_AREA_HPSA_COUNT,

    PCT_UNINSURED,
    UNINSURED_POPULATION,

    PCT_BELOW_POVERTY,
    ESTIMATED_POPULATION_BELOW_POVERTY,

    TOTAL_HPSA_DESIGNATIONS
        / NULLIF(AHRF_POPULATION, 0)
        * 100000
        AS HPSA_DESIGNATIONS_PER_100K

FROM {{ ref('fact_healthcare_access') }}